export * from "./components/artistsTable/artiststable";
export * from "./components/clock/clock";
export * from "./components/footer/footer";
export * from "./components/hero/hero";
export * from "./components/labelsTable/labelstable";
export * from "./components/navBar/navbar";
export * from "./components/drawerCompponent/drawercomponent";
export * from "./components/drawerCompponent/drawerloadingcard";
export * from "./components/searchBar/searchbar";
export * from "./components/logincard/loginCard";
export * from "./components/songsTable/songstable";
export * from "./components/staticBar/staticbar";
export * from "./components/themeButton/themebutton";
export * from "./components/topBar/topbar";
export * from "./components/venuesTable/venuestable";
export * from "./components/currentTable/currentable";
export * from "./components/pagination/pagination";
export * from "./components/map/map";
export * from "./components/linechart/linechart";
export * from "./components/calender/calender";
export * from "./components/moreinfo/moreInfo";
export * from "./components/tableloader/table-loader";
export * from "./components/currentTable/currentable";
export * from "./components/picker/picker";
export * from "./components/currentTableName/currentTableName";
export * from "./components/datePicker/DatePicker";

export * from "./atoms/tablestate";
export * from "./atoms/drawerstate";
export * from "./atoms/isloggedin";
export * from "./atoms/loading";
export * from "./components/navBar/index";
export * from "./components/tempNavBar/temp-nav-bar";
export * from "./atoms/artistsDataState";
export * from "./atoms/labelsDataState";
export * from "./atoms/songsDataState";
export * from "./atoms/venuesDataState";
export * from "./atoms/page";
export * from "./atoms/fromDate";
export * from "./atoms/toDate";
export * from "./atoms/credentials";
export * from "./atoms/chartDataState";
export * from "./atoms/countState";
export * from "./atoms/queryState";
export * from "./atoms/artistTabletState";
export * from "./atoms/labelTabletState";
export * from "./atoms/mapMarkerState";
export * from "./atoms/currentSongState";
export * from "./atoms/searchBarState";

export * from "./selectors/getTablestate";
export * from "./selectors/getdrawerstate";
export * from "./selectors/getArtistsDataState";
export * from "./selectors/getLabelsDataState";
export * from "./selectors/getSongsDataState";
export * from "./selectors/getChartDataState";
export * from "./selectors/getCountState";
export * from "./selectors/getFromDateState";
export * from "./selectors/getToDateState";
export * from "./selectors/getSearchBarState";
export * from "./selectors/getMapMarkerState";

export const BASE_URL =
  "http://ec2-18-169-237-28.eu-west-2.compute.amazonaws.com:3002";

// export const BASE_URL = "http://localhost:3002";
